[package]
name = "dng_sdk_rs"
version = "0.1.0"
edition = "2021"

[features]
dng64bit = []

[dependencies]
const_panic = "0.2.6"
num = "0.4.0"
static_assertions = "1.1.0"
thiserror = "1.0.37"
wide = "0.7.5"


