pub mod color_spec;
pub mod coord;
pub mod illuminant;
pub mod limits;
mod magic;
pub mod matrix;
pub mod point;
pub mod temparature;
pub mod traits;
pub mod types;
pub use types::Result;
pub mod errors;
